import { z } from 'zod';

const optionalUrl = z.union([z.string().url(), z.string().max(500)]).optional();

export const settingsUpdateSchema = z.object({
  companyName: z.string().trim().min(1).max(120).optional(),
  logo: optionalUrl,
  favicon: optionalUrl,
  businessEmail: z.string().email().optional(),
  businessPhone: z.string().min(4).max(30).optional(),
  website: optionalUrl,
  timezone: z.string().min(1).max(80).optional(),
  currency: z.string().min(1).max(10).optional(),
  language: z.string().min(1).max(40).optional(),
  dateFormat: z.string().min(1).max(20).optional(),
  timeFormat: z.string().min(1).max(20).optional(),
  enableMaintenanceMode: z.boolean().optional(),
  businessAddress: z.string().max(250).optional(),
  googleMapsUrl: optionalUrl,
  gstNumber: z.string().max(30).optional(),
  panNumber: z.string().max(30).optional(),
  instagram: optionalUrl,
  facebook: optionalUrl,
  youtube: optionalUrl,
  linkedIn: optionalUrl,
  whatsappNumber: z.string().max(30).optional(),
  emergencyContact: z.string().max(30).optional(),
  businessDescription: z.string().max(2000).optional(),
  bookingPrefix: z.string().max(30).optional(),
  defaultBookingDuration: z.number().int().min(15).max(10080).optional(),
  workingHours: z.string().max(80).optional(),
  workingDays: z.array(z.string()).optional(),
  maximumBookingsPerDay: z.number().int().min(1).max(500).optional(),
  bufferTime: z.number().int().min(0).max(720).optional(),
  bookingConfirmationPolicy: z.string().max(2000).optional(),
  cancellationPolicy: z.string().max(2000).optional(),
  refundPolicy: z.string().max(2000).optional(),
  defaultEventStatus: z.string().max(40).optional(),
  defaultPaymentStatus: z.string().max(40).optional(),
  razorpayKeyId: z.string().max(200).optional(),
  razorpayKeySecret: z.string().max(200).optional(),
  razorpayWebhookSecret: z.string().max(200).optional(),
  depositPercentage: z.number().min(0).max(100).optional(),
  invoicePrefix: z.string().max(30).optional(),
  invoiceFooter: z.string().max(400).optional(),
  invoiceNotes: z.string().max(2000).optional(),
  taxPercentage: z.number().min(0).max(100).optional(),
  lateFee: z.number().min(0).max(100000).optional(),
  enableOnlinePayment: z.boolean().optional(),
  enableCashPayment: z.boolean().optional(),
  enableBankTransfer: z.boolean().optional(),
  smtpHost: z.string().max(200).optional(),
  smtpPort: z.number().int().min(1).max(65535).optional(),
  smtpUsername: z.string().max(200).optional(),
  smtpPassword: z.string().max(200).optional(),
  fromEmail: z.string().email().optional(),
  fromName: z.string().max(120).optional(),
  enableEmailNotifications: z.boolean().optional(),
  twilioAccountSid: z.string().max(200).optional(),
  twilioAuthToken: z.string().max(500).optional(),
  twilioPhoneNumber: z.string().max(30).optional(),
  enableSMS: z.boolean().optional(),
  whatsappBusinessNumber: z.string().max(30).optional(),
  whatsappApiToken: z.string().max(500).optional(),
  webhookUrl: optionalUrl,
  verifyToken: z.string().max(200).optional(),
  enableWhatsApp: z.boolean().optional(),
  dryRunMode: z.boolean().optional(),
  cloudName: z.string().max(200).optional(),
  cloudinaryApiKey: z.string().max(200).optional(),
  cloudinaryApiSecret: z.string().max(200).optional(),
  uploadFolder: z.string().max(200).optional(),
  maxUploadSize: z.number().int().min(1).max(100000).optional(),
  allowedFileTypes: z.array(z.string()).optional(),
  enableImageCompression: z.boolean().optional(),
  primaryColor: z.string().max(20).optional(),
  secondaryColor: z.string().max(20).optional(),
  accentColor: z.string().max(20).optional(),
  sidebarStyle: z.string().max(40).optional(),
  darkMode: z.boolean().optional(),
  lightMode: z.boolean().optional(),
  fontSelection: z.string().max(60).optional(),
  borderRadius: z.number().int().min(0).max(100).optional(),
  animationsEnabled: z.boolean().optional(),
  jwtExpiry: z.number().int().min(60).max(100000).optional(),
  refreshTokenExpiry: z.number().int().min(60).max(100000).optional(),
  sessionTimeout: z.number().int().min(60).max(100000).optional(),
  passwordLength: z.number().int().min(8).max(64).optional(),
  passwordComplexity: z.string().max(40).optional(),
  maxLoginAttempts: z.number().int().min(1).max(20).optional(),
  accountLockDuration: z.number().int().min(1).max(100000).optional(),
  enableTwoFactorAuthentication: z.boolean().optional(),
  enableAuditLogs: z.boolean().optional(),
  enableIpLogging: z.boolean().optional(),
});

export const sanitizeSettingsPayload = (payload: Record<string, unknown>) => {
  const sanitized: Record<string, unknown> = {};
  Object.entries(payload).forEach(([key, value]) => {
    if (value !== undefined) {
      sanitized[key] = value;
    }
  });
  return sanitized;
};
